-- ============================================================================
-- SR10 SETUP QUALITY HYPOTHESIS RESEARCH
-- ============================================================================
--
-- Research outcome:
--   Post-breakout Maximum Favorable Excursion (MFE)
--   over the next 10 trading sessions.
--
-- Research strong-breakout label:
--   MFE_10D >= 5%
--
-- Current mature sample:
--   32 RESOLVED_BREAKOUT episodes
--
-- Additional unresolved validation population:
--   19 RESOLVED_BREAKOUT episodes had not yet accumulated
--   10 future trading sessions as of 2026-09-02.
--
-- --------------------------------------------------------------------------
-- H1
-- --------------------------------------------------------------------------
--
-- A setup exhibiting:
--
--   1. Positive pre-breakout price progression
--        prebreakout_5d_return_pct > 0
--
--   AND
--
--   2. Adequate recent volume participation
--        recent_5_volume_vs_20d_pct >= 90
--
-- near the breakout appears more likely to produce meaningful
-- post-breakout expansion.
--
-- IMPORTANT:
--
--   The 90% volume boundary is PROVISIONAL.
--
--   It was investigated using the same 32-episode research sample and
--   therefore must NOT yet be treated as a production threshold.
--
-- --------------------------------------------------------------------------
-- SUPPORTING EVIDENCE
-- --------------------------------------------------------------------------
--
-- Breakout-day Progression x Volume:
--
--   NEITHER:
--       N = 4
--       Strong rate = 0%
--       Avg MFE = 1.75%
--
--   PROGRESSION_ONLY:
--       N = 9
--       Strong rate = 11.11%
--       Avg MFE = 1.56%
--
--   VOLUME_ONLY:
--       N = 2
--       Strong rate = 0%
--       Avg MFE = 1.94%
--
--   BOTH:
--       N = 17
--       Strong rate = 29.41%
--       Avg MFE = 3.31%
--       Median MFE = 2.65%
--
-- --------------------------------------------------------------------------
-- RANGE / ATR CONTROL
-- --------------------------------------------------------------------------
--
-- Progression + Volume continued to outperform OTHER within both
-- volatility-normalized range regimes.
--
--   P+V / LOWER_RANGE_ATR:
--       N = 5
--       Strong rate = 40%
--       Avg MFE = 4.02%
--
--   P+V / HIGHER_RANGE_ATR:
--       N = 12
--       Strong rate = 25%
--       Avg MFE = 3.01%
--
-- Tightness alone was NOT sufficient to identify strong setups.
--
-- --------------------------------------------------------------------------
-- EPISODE PERSISTENCE
-- --------------------------------------------------------------------------
--
-- Raw constructive-persistence percentage must NOT be interpreted without
-- considering episode observation count.
--
-- Example:
--
--       1 constructive day / 1 observation = 100%
--       5 constructive days / 5 observations = 100%
--
-- These contain very different amounts of evidence.
--
-- No minimum episode-maturity requirement is currently supported.
--
-- --------------------------------------------------------------------------
-- RECENCY
-- --------------------------------------------------------------------------
--
-- Constructive behavior at breakout showed the clearest substantial
-- relationship with subsequent expansion.
--
--   BOTH_LAST_2:
--       N = 6
--       Strong rate = 16.67%
--       Avg MFE = 2.62%
--       Median MFE = 1.81%
--
--   BREAKOUT_DAY_ONLY:
--       N = 11
--       Strong rate = 36.36%
--       Avg MFE = 3.68%
--       Median MFE = 3.41%
--
--   PRIOR_DAY_ONLY:
--       N = 2
--       Strong rate = 0%
--       Avg MFE = 0.63%
--
--   EARLIER_ONLY:
--       N = 3
--       Strong rate = 33.33%
--       Avg MFE = 3.02%
--
--   NONE_RECENT:
--       N = 10
--       Strong rate = 0%
--       Avg MFE = 1.46%
--       Median MFE = 1.01%
--
-- --------------------------------------------------------------------------
-- H2: 52-WEEK-HIGH PROXIMITY
-- --------------------------------------------------------------------------
--
-- Hypothesis:
--
--   Breakouts occurring closer to the stock's 52-week high may produce
--   stronger post-breakout expansion.
--
-- Feature:
--
--   pct_from_52w_high =
--       (adjusted breakout close / highest_high_252 - 1) * 100
--
-- Corporate-action-adjusted prices were used for this analysis.
--
-- Mature RESOLVED_BREAKOUT episodes:
--
--   Total mature episodes             = 32
--   With valid highest_high_252        = 28
--
-- Continuous relationship:
--
--   Correlation with MFE_10D           = -0.141
--   Avg pct_from_52w_high              = -5.36%
--   Avg MFE_10D                        = 2.70%
--
-- Proximity quartiles:
--
--   Q1: -25.38% to -12.29%
--       N = 7
--       Avg MFE = 2.98%
--       Median MFE = 1.07%
--       Strong rate = 28.57%
--
--   Q2: -12.12% to -0.95%
--       N = 7
--       Avg MFE = 3.08%
--       Median MFE = 3.64%
--       Strong rate = 28.57%
--
--   Q3: +0.05% to +0.43%
--       N = 7
--       Avg MFE = 2.27%
--       Median MFE = 1.21%
--       Strong rate = 14.29%
--
--   Q4: +0.70% to +5.93%
--       N = 7
--       Avg MFE = 2.47%
--       Median MFE = 1.60%
--       Strong rate = 14.29%
--
-- Strong-breakout cases occurred across a wide range of 52-week-high
-- proximity, including substantially below the prior high.
--
-- Conclusion:
--
--   H2 is NOT SUPPORTED as an independent predictor of post-breakout
--   expansion in the current mature sample.
--
--   No monotonic improvement in MFE was observed as breakout price moved
--   closer to or above the 52-week high.
--
-- Architectural implication:
--
--   52-week-high proximity may remain useful as a structural / leadership
--   context feature, but current evidence does NOT justify including it as
--   an SR10 setup-quality score or weight.
--
--   Structural leadership context and post-breakout expansion quality
--   should remain separate concerns.
--
-- --------------------------------------------------------------------------
-- H3: TIGHTNESS CONDITIONAL ON PROGRESSION + VOLUME
-- --------------------------------------------------------------------------
--
-- Hypothesis:
--
--   Among setups already exhibiting constructive progression and volume
--   participation, tighter recent price action may produce stronger
--   post-breakout expansion.
--
-- H1-qualified population:
--
--   prebreakout_5d_return_pct > 0
--   AND recent_5_volume_vs_20d_pct >= 90
--
-- Mature H1-qualified episodes:
--
--   N = 17
--   Avg recent_5_range_pct = 6.06%
--   Avg MFE_10D = 3.31%
--
-- Tightness terciles:
--
--   T1: 3.80% to 5.23%
--       N = 6
--       Avg MFE = 3.81%
--       Median MFE = 2.53%
--       Strong rate = 33.33%
--
--   T2: 5.24% to 6.46%
--       N = 6
--       Avg MFE = 3.37%
--       Median MFE = 1.93%
--       Strong rate = 33.33%
--
--   T3: 6.50% to 9.84%
--       N = 5
--       Avg MFE = 2.63%
--       Median MFE = 3.10%
--       Strong rate = 20.00%
--
-- Continuous relationship:
--
--   Correlation(recent_5_range_pct, MFE_10D) = -0.167
--
-- Interpretation:
--
--   Average MFE declined from the tightest to the loosest tercile:
--
--       3.81% -> 3.37% -> 2.63%
--
--   However, median MFE did not show the same monotonic relationship,
--   and the continuous correlation was weak.
--
-- Conclusion:
--
--   H3 is WEAK / INCONCLUSIVE.
--
--   The current sample provides limited directional evidence that tighter
--   recent price action may improve post-breakout expansion after
--   progression + volume qualification, but the evidence is insufficient
--   to establish tightness as an independent SR10 discriminator.
--
-- Architectural implication:
--
--   recent_5_range_pct should remain a tightness / setup-structure feature
--   under SR05.
--
--   Current evidence does NOT justify duplicating SR05 tightness inside
--   SR10 or assigning an SR10 weight based on tightness.
--
-- Research discipline:
--
--   Do NOT optimize additional tightness thresholds on this 17-episode
--   sample. Further evaluation should use new out-of-sample episodes.
--
-- --------------------------------------------------------------------------
-- H4: BREAKOUT-DAY RELATIVE VOLUME INTENSITY
-- --------------------------------------------------------------------------
--
-- Hypothesis:
--
--   Among setups already exhibiting constructive progression and recent
--   volume participation, stronger relative volume on the actual breakout
--   day may produce stronger post-breakout expansion.
--
-- H1-qualified population:
--
--   prebreakout_5d_return_pct > 0
--   AND recent_5_volume_vs_20d_pct >= 90
--
-- Feature:
--
--   breakout_relative_volume = relative_volume_20
--   measured on episode_end_date / breakout date.
--
-- Mature H1-qualified episodes:
--
--   N = 17
--   Avg breakout relative volume = 3.02x
--   Median breakout relative volume = 1.63x
--   Avg MFE_10D = 3.31%
--
-- Continuous relationship:
--
--   Pearson correlation
--       Corr(breakout_relative_volume, MFE_10D) = -0.039
--
--   Spearman rank correlation
--       Corr(rank(breakout_relative_volume), rank(MFE_10D)) = +0.081
--
--   Both relationships are effectively zero.
--
-- Observed strong-breakout cases:
--
--   HINDZINC     RVOL = 0.85x    MFE = 11.22%
--   SHRIRAMFIN   RVOL = 1.24x    MFE =  5.82%
--   HINDALCO     RVOL = 1.63x    MFE =  6.66%
--   SIEMENS      RVOL = 1.75x    MFE =  5.07%
--   BOSCHLTD     RVOL = 5.36x    MFE =  8.73%
--
-- High breakout-day relative volume was not sufficient for strong
-- post-breakout expansion.
--
-- Examples:
--
--   TATACAP      RVOL = 4.00x    MFE = 0.51%
--   ENRIN        RVOL = 20.36x   MFE = 2.20%
--
-- Interpretation:
--
--   Strong outcomes occurred across a wide range of breakout-day relative
--   volume levels.
--
--   The extreme ENRIN observation does not explain the absence of a
--   relationship: Pearson and rank-based Spearman correlations both remain
--   close to zero.
--
-- Conclusion:
--
--   H4 is NOT SUPPORTED.
--
--   Within the current H1-qualified sample, breakout-day relative volume
--   intensity does not independently predict subsequent 10-session MFE.
--
-- Architectural implication:
--
--   Breakout-day relative volume should remain a volume / execution-context
--   feature and should NOT be duplicated as an SR10 setup-quality weight
--   based on the current evidence.
--
--   This result does not invalidate the H1 volume-participation observation.
--   H1 measures recent setup context, whereas H4 tests the intensity of
--   volume specifically on the breakout day.
--
-- Research discipline:
--
--   Do NOT optimize breakout-relative-volume thresholds (for example
--   1.5x, 2x or 3x) on this 17-episode sample. Further testing should use
--   new out-of-sample episodes.
--
-- --------------------------------------------------------------------------
-- ARCHITECTURAL CONCLUSIONS
-- --------------------------------------------------------------------------
--
-- 1. Progression and volume participation should be treated as interacting
--    setup-quality dimensions rather than independent additive flags.
--
-- 2. Tightness alone is not sufficient.
--
-- 3. Lower pivot-to-stop risk is not currently supported as a predictor
--    of post-breakout expansion. Risk remains a separate risk-management
--    dimension.
--
-- 4. Volume dry-up and constructive volume participation answer different
--    questions. Do NOT redefine SR06 using this research.
--
-- 5. Episode persistence alone is not sufficient.
--
-- 6. No minimum episode length is currently justified.
--
-- 7. Recency, especially conditions around breakout, appears more useful
--    than simple whole-episode persistence.
--
-- 8. Do NOT create an SR10 production score/table from H1 yet.
--
-- --------------------------------------------------------------------------
-- VALIDATION PLAN
-- --------------------------------------------------------------------------
--
-- Freeze H1 at this point.
--
-- Do NOT optimize the 90% volume threshold further using the existing
-- 32 mature episodes.
--
-- Allow currently immature RESOLVED_BREAKOUT episodes to accumulate
-- 10 future trading sessions.
--
-- Test H1 against that later population as an out-of-sample validation.
--
-- Only after validation should thresholds, scoring, weighting and the
-- physical SR10 production architecture be considered.
--
-- ============================================================================